### ISSUE TITLE
Move old VCS text

### ISSUE THREAD

**Issue by Nakhr11n** [DescentDevelopers/Descent3#100]
The old VCS text in most source files is in the way of the code.
But it is useful to keep it around for context, just not in the source files themselves.

For example it could be put in an adjacent file:
`Descent3/LoadLevel.cpp` (1200 lines of old VCS)
`-> Descent3/LoadLevel.cpp.old-vcs`

**Comment by winterheart** [comment]
I don't think that extracting old changelogs from source files into another is good idea. In other hand, they dot not affects on building of project. I'd keep them in source for historical purpose.

**Comment by th1000s** [comment]
Most IDEs hide the first comment, expecting it to be some uninteresting copyright blurb - but here it is the historical VCS log.

Unfortunately, this just broke when @kevinbentley added an _actual_ GPLv3 header :). This could be remedied by joining these two comments with a  `----` separator and maybe adding a note that these are historical so nobody extends or modifies them.

**Comment by JeodC** [comment]
> Most IDEs hide the first comment, expecting it to be some uninteresting copyright blurb - but here it is the historical VCS log.
> 
> Unfortunately, this just broke when @kevinbentley added an _actual_ GPLv3 header :). This could be remedied by joining these two comments with a `----` separator and maybe adding a note that these are historical so nobody extends or modifies them.

I like this, although I'm not sure if license headers are required to be in their own comment section. If this is ok to do, perhaps a script could be made to walk through everything with ease.
