### ISSUE TITLE
Multiplayer needs testing

### ISSUE THREAD

**Issue by JeodC** [DescentDevelopers/Descent3#107]
Multiplayer games could do with cross-platform testing. A windows server is being hosted at `64.44.131.41` - Dmax Chicago v1.5 test

**Comment by bryanperris** [comment]
Probably should test on the local LAN first, which is simply running 2 D3 instances on 2 separate machines connected to the same LAN.  The firewall on your router could simply be blocking ports on WAN.

**Comment by JeodC** [comment]
> Probably should test on the local LAN first, which is simply running 2 D3 instances on 2 separate machines connected to the same LAN.  The firewall on your router could simply be blocking ports on WAN.

If it is a firewall issue, there needs to be an error message.

**Comment by bryanperris** [comment]
It depends on what kind of socket you are opening, if its UDP, you simply don't care if it is blocked or not, you send out a packet no matter what.  If it is TCP, then yeah, the connection handshake will fail, in return you receive some kind of error from networking stack.

**Comment by JeodC** [comment]
In v1.4 for the steam version I was able to type in an IP address and hit enter to get the server info to appear. In current builds it does nothing. I'm told this is due to a protocol change, but I haven't seen any documentation for it.

**Comment by JeodC** [comment]
I ran a dedicated server on a laptop and was able to connect to it. This appears to just be a matter of having some updated dedicated servers.

**Comment by JeodC** [comment]
> What we don't know is, if the dedicated servers have been setup based on how the private updated repo works.

I updated the OP with a test server. We should verify all platforms are able to connect to it and ideally have multiple clients connected at once for a playtest or two.

**Comment by JamesTKhan** [comment]
Grabbing the latest build artifacts I was able to connect to the server on a Windows machine by typing in the IP address. I can probably be open for a play test depending on the time.

**Comment by JeodC** [comment]
> Grabbing the latest build artifacts I was able to connect to the server on a Windows machine by typing in the IP address. I can probably be open for a play test depending on the time.

@InsanityBringer is releasing a modernized fork of Descent 3 soon I believe. Since the community is for the most part waiting on playing the game until it feels more natural, perhaps that release would be a good test bed for cross-platform multiplayer.

**Comment by DescentMax** [comment]
I have a couple servers I can host for testing. Be more than happy to do this. One in Chicago and one in Colorado

**Comment by DescentMax** [comment]
okay I have 2 servers running the latest build (as of 4.27.2024) on 2 servers:
Chicago: 64.44.131.41:2092

Colorado: 96.9.208.115:2092

They are running, but for some reason they are not reporting to the trackers. When I revert back to 1.4 they post so Im still investigating on why, but they ARE running. If you cant get in, please let me know

**Comment by Snyper587** [comment]
I'll try to help with this. If you click the "Search For Games At Address:" it looks like it presents the server details. I joined the server on my Widnows box and looks like it's working fine. Will see if I can dig out one of my Ubuntu boxes from the closet and give it a test.

![image0](https://github.com/DescentDevelopers/Descent3/assets/168311034/b8d3d996-2e5e-4afa-9a00-cb471a8e20c5)
![image1](https://github.com/DescentDevelopers/Descent3/assets/168311034/748af86f-06f3-41d5-95c1-c401d64231b9)

https://github.com/DescentDevelopers/Descent3/assets/168311034/e823e661-9f3b-4e95-9d7b-61115350bee5
