### ISSUE TITLE
Port D3Edit to Linux/Mac

### ISSUE THREAD

**Issue by DMJC** [DescentDevelopers/Descent3#125]
Obviously this is a long time into the future, but it would be awesome if the D3Edit level editor had a port. The Freespace2 SCP team are rewriting FRED2 using QT and porting it to Mac and Linux.

**Comment by JeodC** [comment]
D3Edit will eventually be integrated into this repository. For now, though, it exists [here](https://github.com/DescentDevelopers/D3Edit) and is as of writing untouched. I'm more than happy to adjust labels and whatnot if it starts seeing some activity, but for now this issue belongs over there.
