### ISSUE TITLE
Enable console logging

### ISSUE THREAD

**Issue by JeodC** [DescentDevelopers/Descent3#157]
Per Kevin Bentley, it may be wise to modify cmake to do `-DCMAKE_BUILD_TYPE=debug` or `-DLOGGER`. Log output to the console for better linux/mac troubleshooting. Perhaps provide instructions to the user in an issue template on how to utilize it.

**Comment by jcoby** [comment]
logging was removed in #77 because the `mprintf_at` macro wasn't expanding to `Debug_ConsolePrintf(int n, int row, int col, char *format, ...)` and causing a segfault. #159 reenables the option, renames the function to `Debug_ConsolePrintfAt` and adds the LOGGER define as well.

**Comment by winterheart** [comment]
Perhaps this issue may be considered as solved?

**Comment by JeodC** [comment]
> Perhaps this issue may be considered as solved?

That's what I'm wondering. I think it's ok to merge.
