### ISSUE TITLE
Checksum failure on 64 bit builds causes script load failure

### ISSUE THREAD

**Issue by jcoby** [DescentDevelopers/Descent3#160]
### Build Version

86a6c139ee9b71ffa2a043a1778765367ee0652e

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [X] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [ ] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [X] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Description

Scripts do not pass checksum when built on MacOS. Might also affect other 64-bit builds:

`Game-Checksum FAIL!!! (2273889867l!=2273873307l)`

`Osiris_CreateGameChecksum` does several `sizeof` calls and a bit of math to figure out the game state and compares that value to the compiled in `CHECKSUM` define to see if scripts were compiled against a different version of the game.

We'll need to come up with a portable `Osiris_CreateGameChecksum` function or hardcode the value on 64-bit machines as a workaround.

Use this patch as a temporary workaround:

```diff --git a/Descent3/OsirisLoadandBind.cpp b/Descent3/OsirisLoadandBind.cpp
index 20f52d8..0056c35 100644
--- a/Descent3/OsirisLoadandBind.cpp
+++ b/Descent3/OsirisLoadandBind.cpp
@@ -1,5 +1,5 @@
 /*
-* Descent 3
+* Descent 3
 * Copyright (C) 2024 Parallax Software
 *
 * This program is free software: you can redistribute it and/or modify
@@ -630,6 +630,10 @@ void Osiris_InitModuleLoader(void) {
 //     so they can use to compare to the time when they were compiled, to see
 //     if they are compatible.
 uint Osiris_CreateGameChecksum(void) {
+  #if defined(__aarch64__)
+  return 2273873307l;
+  #endif
+
   uint value = 0xe1e1b0b0;

   value += sizeof(object);
```

**Comment by winterheart** [comment]
Checksum is calculated based on size of various structures and objects. Some of them has members with long or ulong type with 8 bytes long instead 4 on 32 bit, so on 64 bit we have different size and different checksum. Need to carefully examine Osiris structures involved to checksum calculation and replace (u)long to (u)int32_t from cstdint.

**Comment by jcoby** [comment]
> Checksum is calculated based on size of various structures and objects. Some of them has members with long or ulong type with 8 bytes long instead 4 on 32 bit, so on 64 bit we have different size and different checksum. Need to carefully examine Osiris structures involved to checksum calculation and replace (u)long to (u)int32_t from cstdint.

I think the bigger problem is going to be pointers. AFAIK there isn't a way to get 32 bit pointers on aarch64 so we'll always be adding 4 bytes there.

**Comment by winterheart** [comment]
> > Checksum is calculated based on size of various structures and objects. Some of them has members with long or ulong type with 8 bytes long instead 4 on 32 bit, so on 64 bit we have different size and different checksum. Need to carefully examine Osiris structures involved to checksum calculation and replace (u)long to (u)int32_t from cstdint.
> 
> I think the bigger problem is going to be pointers. AFAIK there isn't a way to get 32 bit pointers on aarch64 so we'll always be adding 4 bytes there.

Yeah, this too.

**Comment by bryanperris** [comment]
Here are my thoughts:
For all platforms use the `d3-linux.hog` concept that we effectively can move away from BOA checksum system

Then update how the level scripts hog filename is generated based on the build environment:

Microsoft Windows Visual C++: d3scripts-win32 or d3scripts-win64.hog
Platforms using GCC/Clang: d3scripts-<triple target>.hog
Mac with Xcode: d3scripts-<whatever xcode decides to use for target names>.hog

**Comment by winterheart** [comment]
Checksums here is way to determine that nothing changed on ABI level of Osiris subsystem. On updating scripting system without checksums we cannot say that certain script in hog file can actually executed.

**Comment by bryanperris** [comment]
I get that, but going forward we only need to manage a spec version since rather then depending on struct sizes, it is just a hacky solution to being with and not worth to maintain between various platforms. Eventually the scripting system is going to be replaced with a WebAssembly based one, and with that, the modules just need conform to some versioned spec check as well.

**Comment by JeodC** [comment]
> Eventually the scripting system is going to be replaced with a WebAssembly based one

FWIW, that isn't set in stone yet though it's currently the top choice it appears.
