### ISSUE TITLE
[Question] Legacy Support?

### ISSUE THREAD

**Issue by OpenRift412** [DescentDevelopers/Descent3#164]
Will the updated version of Descent 3 still be compatible with legacy OSs and APIs (3DFX Glide, Creative EAX, etc.), or will those be left behind entirely in the name of modernization?

The main reason I ask is in the name of multiplayer between people playing on legacy and modern systems.

If this is out of scope, what about making 1.5 multiplayer cross-compatible with the old 1.4 version? Would that be more doable?

**Comment by JeodC** [comment]
The current mission is a 1.5 release if it had reached completion in 2000. Any modernization changes will come after that point. It's a "cross that bridge when we get there" thing--pushing off answering those questions keeps things on track.

**Comment by JeodC** [comment]
This also means some modern systems like the Mac M1/M2 may not work properly yet.

**Comment by OpenRift412** [comment]
> The current mission is a 1.5 release if it had reached completion in 2000. Any modernization changes will come after that point. It's a "cross that bridge when we get there" thing--pushing off answering those questions keeps things on track.

Alright, well just as a note: it seems that Glide wrappers such as dgVoodoo2 and EAX wrappers such as Creative's ALchemy seem to cause the game to lock up. It will get stuck at the error log window thing and then I can't select yes or no.

**Comment by JeodC** [comment]
> > The current mission is a 1.5 release if it had reached completion in 2000. Any modernization changes will come after that point. It's a "cross that bridge when we get there" thing--pushing off answering those questions keeps things on track.
> 
> 
> 
> Alright, well just as a note: it seems that Glide wrappers such as dgVoodoo2 and EAX wrappers such as Creative's ALchemy seem to cause the game to lock up. It will get stuck at the error log window thing and then I can't select yes or no.

Please file that as a separate issue and we'll give it our best effort. No promises though especially if it was broken in the historical branch. Progress is natural after all; if modernizing ends up meaning dropping legacy then it'll have to happen.

**Comment by OpenRift412** [comment]
> > > The current mission is a 1.5 release if it had reached completion in 2000. Any modernization changes will come after that point. It's a "cross that bridge when we get there" thing--pushing off answering those questions keeps things on track.
> > 
> > 
> > Alright, well just as a note: it seems that Glide wrappers such as dgVoodoo2 and EAX wrappers such as Creative's ALchemy seem to cause the game to lock up. It will get stuck at the error log window thing and then I can't select yes or no.
> 
> Please file that as a separate issue and we'll give it our best effort. No promises though especially if it was broken in the historical branch. Progress is natural after all; if modernizing ends up meaning dropping legacy then it'll have to happen.

Scratch that, I don't know what I did but it seems that I don't get that error anymore, but it seems like there's another problem, which I'll make a new issue for.

**Comment by OpenRift412** [comment]
Actually @JeodC I'll just tell you here, since it's still on-topic for this issue.

So when testing again with both dgVoodoo2's Glide and Direct3D wrappers, it seems that the game isn't really acknowledging them at all. I'm not much of a programmer, so I looked at the new EXE in a hex editor and compared it to the original 1.4 version, finding that there wasn't any mention of the string "glide" in the new EXE. I don't know if this was a change found in the original unfinished version of 1.5, but searching "glide" in the repo seems to still show results, but I'm not seeing any comments or anything regarding disabling the API. Was this stripped out?

Regardless, I don't know why it doesn't acknowledge the D3D wrapper tho, since "d3d" has the same number of string occurrences in the new EXE as it did in 1.4.

**Comment by JeodC** [comment]
> Actually @JeodC I'll just tell you here, since it's still on-topic for this issue.
> 
> So when testing again with both dgVoodoo2's Glide and Direct3D wrappers, it seems that the game isn't really acknowledging them at all. I'm not much of a programmer, so I looked at the new EXE in a hex editor and compared it to the original 1.4 version, finding that there wasn't any mention of the string "glide" in the new EXE. I don't know if this was a change found in the original unfinished version of 1.5, but searching "glide" in the repo seems to still show results, but I'm not seeing any comments or anything regarding disabling the API. Was this stripped out?
> 
> Regardless, I don't know why it doesn't acknowledge the D3D wrapper tho, since "d3d" has the same number of string occurrences in the new EXE as it did in 1.4.

Again please open a new issue for this. We have templates to keep things neat and tidy--they enable better progress and more community involvement as you can see with #141. This hasn't been reported before so we need the information the template provides--the platform, architecture, reproduction steps etc.
