### ISSUE TITLE
[ Control Configuration ] - The side mouse buttons cannot be bound to an action

### ISSUE THREAD

**Issue by DAK404** [DescentDevelopers/Descent3#187]
Summary: The side mouse buttons cannot be bound to an action (Switch primary, switch secondary, etc.)

Platform: Windows 11 64 Bit
Architecture: x86_64

Steps to check:

- Open Game
- Choose Pilot
- Options -> Config -> Mouse
- Try to bind the mouse side button to an action (does not work as of now: 26-April-2024)

Note:
While creating a new pilot, I chose `default keyboard` option.

Please let me know if there are any log files or additional data is required to be captured and uploaded.

**Comment by Lgt2x** [comment]
Let's keep the issue open to solve that when we migrate framework!

**Comment by DAK404** [comment]
Piccu Engine v1.0.1 supports mouse side buttons!

**Comment by JeodC** [comment]
> Piccu Engine v1.0.1 supports mouse side buttons!

That's cool, but unfortunately we can't bring it over just yet because of pending sdl changes, which may make it incompatible. We'll visit this when we're ready, don't worry. :)

**Comment by icculus** [comment]
> That's cool, but unfortunately we can't bring it over just yet because of pending sdl changes, which may make it incompatible. We'll visit this when we're ready, don't worry. :)

Were Piccu Engine's fixes for this only in the Windows-specific code? You should get them in there, even if we end up moving Windows to SDL2 as well, as that might take a little time.

**Comment by JeodC** [comment]
> > That's cool, but unfortunately we can't bring it over just yet because of pending sdl changes, which may make it incompatible. We'll visit this when we're ready, don't worry. :)
> 
> Were Piccu Engine's fixes for this only in the Windows-specific code? You should get them in there, even if we end up moving Windows to SDL2 as well, as that might take a little time.

Good catch, I didn't look at it close enough. Thanks!
