### ISSUE TITLE
[Runtime Issue]: Render effects missing

### ISSUE THREAD

**Issue by JeodC** [DescentDevelopers/Descent3#193]
### Description

In Direct3D, some special rendering effects such as specular highlights, lighting, reflections etc are used, but in OpenGL they are missing. Images below show the differences. The first two images showcase the effects in Direct3D rendering. The final image showcases how the game renders in OpenGL.

![image](https://github.com/DescentDevelopers/Descent3/assets/47716344/45621316-ebdc-49e8-8a06-27b2ce17a023)
![image](https://github.com/DescentDevelopers/Descent3/assets/47716344/2a67fabb-6399-4e2c-8a1a-46d2f084e521)

![image](https://github.com/DescentDevelopers/Descent3/assets/47716344/2d4bde1b-f178-470d-babf-4602b471dcf7)

Modern times call for modern solutions. Document what is happening here and, if possible, enable it on OpenGL, which should be able to handle all of this in the current year.

**Comment by JeodC** [comment]
This was done via the `-bumped` CLI and would only work on the Direct3D renderer. Maybe it can be ported to OpenGL.

**Comment by jmarshall23** [comment]
Already working finishing a version of this in my fork, I'll bring it over to mainline when its ready to go.
