### ISSUE TITLE
Find game files outside of the Executable directory

### ISSUE THREAD

**Issue by Lgt2x** [DescentDevelopers/Descent3#202]
Currently, D3 looks for HOG files only in the same directory as the executable. This is not very practical during development, as it requires either copying game files to the build directory, or copying the built executable to the game directory.

We need to provide a way to avoid copying files around to run the game. For this, we could have 2 complementary solutions :
- Create a CMake option to specify the default directory(ies) where the game should try to find the game files.
- Provide a new command line option to specify at runtime the location where game files are located. This would override the CMake option.

Any other solutions you would like to see implemented ? Note that this does not replace creating a proper installer for the game, which we will do at some point

**Comment by Lgt2x** [comment]
Actually `-setdir` should already solve part of the problem https://github.com/DescentDevelopers/Descent3/wiki/Running-Descent-3#command-line-options

**Comment by bryanperris** [comment]
We can also include a cmake way to deploy the build artifacts to your game directory, eg: setting prefix.

**Comment by Lgt2x** [comment]
`-setdir` is satisfying until we get to packaging
