### ISSUE TITLE
The Descent 3 Source build with cmake settings supports minimum Cmake v.3.20

### ISSUE THREAD

**Issue by vitosky66** [DescentDevelopers/Descent3#208]
### Build Version

v.1.5

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Description

The Descent 3 Source build with cmake settings supports minimum Cmake v.3.20, so you need to use Visual Studio 2019 or 2022, I have checked with Visual Studio 2017 and  it's use Cmake v.3.12.
Unless you can change the version, is possible?
This in the line in CMakelists.txt file: cmake_minimum_required(VERSION 3.20)  # For using CMAKE_<LANG>_BYTE_ORDER

I don't know

**Comment by winterheart** [comment]
You can try to install cmake separately in Windows and make changes in MSVC to use external cmake (maybe, I guess?). Generally updating MSVC to 2022 is advised since this version is our currently supported toolchain on Windows, and I can't guarantee that 2017 fully supports C++17 standard.
