### ISSUE TITLE
Improve spdlog integration

### ISSUE THREAD

**Issue by Lgt2x** [DescentDevelopers/Descent3#248]
Minimal spdlog support has been merged in #212 . For wider support in the game, we now need to:
 - Add developer doc in the wiki for usage
 - Add a command-line to output to file
 - Add CLI option to use it in Release mode ?
 - Convert most debug printf to using it
More ?

@bryanperris @JeodC

**Comment by bryanperris** [comment]
log levels info, error, warn should already be available in release builds.  I do plan on replacing all those printf stuff with this logging system.  Anything being printed to the terminal should now be captured by the log system instead.  

I already plan to do more PRs that will start logging out more details of various things (eg: the level loading stuff should have trace prints)

**Comment by winterheart** [comment]
I think we may make all logging levels available for users, as this may be useful for issue reporting.
Definetly we should create relevant CLI and config options both for log level and log file path.

**Comment by JeodC** [comment]
Related: #271

**Comment by JeodC** [comment]
Since spdlog was changed entirely, is this issue relevant?

**Comment by winterheart** [comment]
Closing as spdlog support was removed.
