### ISSUE TITLE
[Build Failure]: 

### ISSUE THREAD

**Issue by GravisZro** [DescentDevelopers/Descent3#249]
### Build Version

d3b0bb744be938e3bb366b4ebd38fe4f57b646c4

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Description

I suggest you reconsider my suggestion of rebasing instead of merging. #228

```
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.

```

### Regression Status

oldest: d3b0bb744be938e3bb366b4ebd38fe4f57b646c4
newest: 27eadbf66b42b2ccfd5ff043dbc24a2edc665bb1

### Steps to Reproduce

git clone git@github.com:DescentDevelopers/Descent3.git D3upstream
cd D3upstream/
cmake --preset linux

**Comment by winterheart** [comment]
You need install additional package spdlog-dev (in Debian/Ubuntu) as it new dependency required for building project (#212).

**Comment by GravisZro** [comment]
Why wasn't this mentioned in the git log?!

**Comment by winterheart** [comment]
It was documented in README.md in relevant commit. In doubt always refer to README, we always keeping it in sync with current state of development.
