### ISSUE TITLE
Implementing own version of MVE library

### ISSUE THREAD

**Issue by winterheart** [DescentDevelopers/Descent3#253]
This issue is an intermediate result of what the team has been discussing since the start of development. The original Descent 3 code was supplied with the Interplay's MVE library, which has an unknown licensing status. During the discussion, we decided to adapt one of the open MVE implementations available under GPL3-compatible licenses. For reference, see issue #2.

Originally, Descent 1 and 2 had their source code released in ~1999, licensed by Parallax with the "no revenue" clause and did not include Interplay MVE libraries. D2X project is derived from Descent 2 codebase and developed own implementation of MVE under GPLv3 license. DXX-Rebirth derived from D2X and has a C++20 MVE library - which is also GPLv3 (see additional explanations on licensing status from [DXX-Reburth developer](https://github.com/dxx-rebirth/dxx-rebirth/issues/774)).

As a result, it was decided to use the original implementation from D2X (https://github.com/btb/d2x/tree/main/libmve) available under GPL3 license.

Now we begin work on the actual implementation.

**Comment by bryanperris** [comment]
What is the status of this?
