### ISSUE TITLE
[Runtime Issue]: Case sensitive filesystems encountering errors

### ISSUE THREAD

**Issue by Jayman2000** [DescentDevelopers/Descent3#262]
### Build Version

v1.5.0 0254bec

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [ ] Single player
- [X] Anarchy
- [X] Hyper-Anarchy
- [X] Robo-Anarchy
- [X] Team Anarchy
- [X] Capture the Flag
- [X] Bounty
- [X] Entropy
- [X] Hoard
- [X] Monsterball
- [X] Cooperative

### Game Environment

The game data is from a fresh installation of the Windows Dual-Jewel version of Descent 3 that has been updated to v1.4.

I’m running NixOS 23.11.

### Description

If you build game with `ENABLE_LOGGER` set to `ON`, then this message will get logged:

```
PPIC: Error opening PPics.Hog database
```

It appears the the name of the file is case sensitive. When I installed Descent 3 in Wine, it named the file `PPICS.HOG`, but the game wants it to be named ` PPics.Hog`. I was able to workaround this issue by running `ln -s PPICS.HOG PPics.Hog`

### Regression Status

All I know is that this bug doesn’t happen when I run the Windows version of Descent 3 v1.4 in Wine.

### Steps to Reproduce

1. Build the game with the logger enabled.
2. Put a copy of the game in a case sensitive directory.
3. Start the game. While the game is starting, the previously mentioned PPIC error will get logged.
4. Create a new pilot named “dopefish”.
5. Attempt to select a pilot picture for that pilot. The game will tell you that there are no pilot pictures for that pilot. It should give you a menu to select dopefish’s pilot picture.

**Comment by JeodC** [comment]
There are several files the game opens and reads. We will need to add case insensitivity to all of them.

**Comment by JeodC** [comment]
Here is a rough list of what needs changes to case insensitivity:

- PPics.hog - [PilotPicsAPI.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/PilotPicsAPI.cpp#L75)
- d3demo.hog - [init.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/init.cpp#L1678)
- d3.hog - [init.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/init.cpp#L1678)
- d3-linux.hog - [init.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/init.cpp#L1678)
- d3-osx.hog - [init.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/init.cpp#L1678)
- extra.hog - [init.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/init.cpp#L1678)
- extra1.hog - [init.cpp]()
- merc.hog - [init.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/init.cpp#L1678)
- extra13.hog - [init.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/init.cpp#L1678)
- level1.mve [menu.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/init.cpp#L1678)
- intro.mve [descent.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/descent.cpp#L530)
- intro.mve [descent.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/descent.cpp#L906)
- various [descent.cpp](https://github.com/DescentDevelopers/Descent3/blob/0254bec63648e3feb40b97d8c1a2a121815bba0a/Descent3/descent.cpp#L871)

**Comment by phlash** [comment]
OK folks, I have searched through the tree for all uses of `open()` and `fopen()`, then assessed if they need to be case insensitive by looking at the callers and purposes, ugly results in attached files, TL;DR as hinted by @JeodC above:

 * `movie/d3movie.cpp: mve_PlayMovie(), mve_SequenceStart()`
 * `cfile/cfile.cpp: cf_OpenLibrary()`

Usefully there is already a `cf_FindRealFileNameCaseInsensitive()` which I shall try first to resolve supplied names.

[opens.txt](https://github.com/DescentDevelopers/Descent3/files/15221536/opens.txt)
[fopens.txt](https://github.com/DescentDevelopers/Descent3/files/15221537/fopens.txt)
