### ISSUE TITLE
Anti-aliasing options

### ISSUE THREAD

**Issue by Jayman2000** [DescentDevelopers/Descent3#265]
It would be nice if there were in-game anti-aliasing options.

**Comment by JeodC** [comment]
Please don't clog the issues board with enhancement wishlists. We created the roadmap for a reason.

**Comment by Jayman2000** [comment]
What’s the correct way to make a feature request?

**Comment by JeodC** [comment]
You shouldn't until we're actively working on rendering components. Piccu engine is focused on render improvements currently. You can try that if you're impatient.

**Comment by Jayman2000** [comment]
> You shouldn't until we're actively working on rendering components.

Why not?
