### ISSUE TITLE
[README Issue]: package "spdlog-dev" does not exist

### ISSUE THREAD

**Issue by GravisZro** [DescentDevelopers/Descent3#267]
### Description

So, I copied the command from the README.md file to install the required pacakges:
`sudo apt install -y --no-install-recommends ninja-build cmake g++ libsdl1.2-dev libsdl-image1.2-dev libncurses-dev libxext6:i386 zlib1g-dev spdlog-dev`

it ends with `spdlog-dev`, a package that doesn't exist on [Debian](https://packages.debian.org/search?keywords=spdlog-dev&searchon=names&suite=all&section=all) or [Ubuntu](https://packages.ubuntu.com/search?keywords=spdlog-dev&searchon=names&suite=all&section=all).

Also, there is no way to correctly report this bug.  There should be an issue template for stuff like this.

**Comment by JeodC** [comment]
Pending #261.
