### ISSUE TITLE
[Runtime Issue]: Fullscreen causes entire system to lock up

### ISSUE THREAD

**Issue by Jayman2000** [DescentDevelopers/Descent3#278]
### Build Version

v1.5.0 0e55dee

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [X] Anarchy
- [X] Hyper-Anarchy
- [X] Robo-Anarchy
- [X] Team Anarchy
- [X] Capture the Flag
- [X] Bounty
- [X] Entropy
- [X] Hoard
- [X] Monsterball
- [X] Cooperative

### Game Environment

The game data is from a fresh installation of the Windows Dual-Jewel version of Descent 3 that has been updated to v1.4.

I’m running [NixOS](https://nixos.org) 23.11.

### Description

If I launch the game in fullscreen mode, then my screen goes blank. The game doesn’t make any sound. The mouse and keyboard don’t seem to do anything. I can’t <kbd><kbd>Alt</kbd> + <kbd>Tab</kbd></kbd> out of the game. I can’t use <kbd><kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>F1</kbd></kbd> to switch to a TTY.

If I SSH into my machine and SIGKILL Descent 3, it doesn’t fix the problem. I have to SSH into my system and run `systemctl reboot` in order to get back to my desktop.

Here’s a log: <https://gist.github.com/Jayman2000/96572b5c2e61048ccbfdc7ef83b3c10e>

### Regression Status

I don’t know.

### Steps to Reproduce

1. Launch the game in fullscreen mode.

**Comment by JeodC** [comment]
Those int3s only occur during movies. Do you have movies?

**Comment by Jayman2000** [comment]
> Do you have movies?

Yes.

**Comment by JeodC** [comment]
> > Do you have movies?
> 
> 
> 
> Yes.

If you do --no intro or remove the intro.mve file, does it work?

**Comment by JeodC** [comment]
Actually if it's affecting movies it's best to just rename the movies folder as a test. The title screen still loads mainmenu.mve.

**Comment by Jayman2000** [comment]
> Actually if it's affecting movies it's best to just rename the movies folder as a test. The title screen still loads mainmenu.mve.

OK. I renamed the movies folder to movies-ignore, but the same thing still happened. Here’s the log for this second attempt: <https://gist.github.com/Jayman2000/8655cff23297ebe854434050984910a6>

**Comment by JeodC** [comment]
> > Actually if it's affecting movies it's best to just rename the movies folder as a test. The title screen still loads mainmenu.mve.
> 
> OK. I renamed the movies folder to movies-ignore, but the same thing still happened. Here’s the log for this second attempt: https://gist.github.com/Jayman2000/8655cff23297ebe854434050984910a6

Can you try some earlier build artifacts for regression? We haven't touched much besides the movies, and the crash appears to occur right after the renderer loads.

**Comment by Jayman2000** [comment]
> Can you try some earlier build artifacts for regression? We haven't touched much besides the movies, and the crash appears to occur right after the renderer loads.

Instead of testing build artifacts, would it be OK if I rebuilt older versions of the game from source? It’s easier to build from source than it is to run prebuilt binaries on NixOS. Also when I do the tests, should I keep the movies folder renamed, or should I switch it back to its original name?

**Comment by Jayman2000** [comment]
> @Jayman2000 can you attach a debugger and get a backtrace?

Here it is. The backtrace is at the bottom of  this log: <https://gist.github.com/Jayman2000/5c5532ed243e7dbbfa11b689b6ccef4b>

**Comment by JeodC** [comment]
It fails on changing screen resolution. We haven't gotten to that point yet, but PiccuEngine should get past it.

**Comment by JeodC** [comment]
> > @Jayman2000 can you attach a debugger and get a backtrace?
> 
> Here it is. The backtrace is at the bottom of this log: https://gist.github.com/Jayman2000/5c5532ed243e7dbbfa11b689b6ccef4b

We don't support NixOS so we won't look too deep into this--it may even go away in the future once we make the switch to SDL2. Based on the backtrace, though, I can offer a few hints. It's hanging at the `poll()` function call within the C library, occurring in `SDL_SetVideoMode()`. That function occurs at `SDL_Surface *surface = SDL_SetVideoMode(*width, *height, 32, flags);`. Look into the variables being passed, if any.
