### ISSUE TITLE
[Runtime Issue]: Render depth resets to lowest on map edge

### ISSUE THREAD

**Issue by donotsharepersonalinformation** [DescentDevelopers/Descent3#280]
### Build Version

0e55dee0dec22b2895f14beb0c789bbbd489d5c3

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Game Environment

Descent 3: Retribution, Map 2.
When you exit out to the surface and get to the large open area this becomes most noticeable. 

### Description

The Render Depth for me is being reset from the highest (100) to the lowest (40) setting when touching the map edge between the ground and space. It doesn't seem to be consistent when happening, but flying around and wedging myself on the map edge was the best way to make this happen. 

### Regression Status

I don't know.

### Steps to Reproduce

1. Set your Render Depth to 100
2. Load map 2 for the base campaign (Descent 3: Retribution)
3. Play the map till you go out into the wide open crater.
4. Wedge yourself into the edge of the map (between ground and space)
5. If you are looking at a spot far enough away it will disappear when it happens.
6. Looking at your Render Depth will show that it has been set to 40

**Comment by devint1** [comment]
It seems to come from [here](https://github.com/DescentDevelopers/Descent3/blob/main/Descent3/TerrainSearch.cpp#L442), bumping `MAX_CELLS_TO_RENDER` seems to fix it

**Comment by JeodC** [comment]
> It seems to come from [here](https://github.com/DescentDevelopers/Descent3/blob/main/Descent3/TerrainSearch.cpp#L442), bumping `MAX_CELLS_TO_RENDER` seems to fix it

It does, but that's render distance, not render depth. If they're the same thing, that's confusing. Also, if they're the same thing, why is it being reset to 40? That would mean `TERRAIN_SIZE` = 0.5. Over in [terrain.h](https://github.com/DescentDevelopers/Descent3/blob/ed385adb5965e50200efb515c0eb3463ab60a763/Descent3/terrain.h#L33) that's defined as 16, and seemingly not modified elsewhere unless by the level.

**Comment by JeodC** [comment]
```cpp
#define MAX_CELLS_TO_RENDER 60000 // The maximum number of cells we can render in a frame

#define MAX_TERRAIN_HEIGHT 350.0f                              // Max height of our terrain
#define TERRAIN_HEIGHT_INCREMENT (MAX_TERRAIN_HEIGHT / 255.0f) // Incremental jumps
#define DEFAULT_VISIBLE_TERRAIN_DISTANCE 150.0 * TERRAIN_SIZE
```

```cpp
  if (*ccount >= MAX_CELLS_TO_RENDER) {
    mprintf((0, "Trying to render too many cells!  Cell limit=%d\n", MAX_CELLS_TO_RENDER));
#ifndef NEWEDITOR
    //Detail_settings.Terrain_render_distance = 120.0 * TERRAIN_SIZE;
#endif
    return;
  }
  ```

This modification makes for a very comfortable render distance and disables the game resetting it, which IMO shouldn't happen in the first place.

![image](https://github.com/DescentDevelopers/Descent3/assets/47716344/46c51304-fd64-422a-9fe5-e6f524938c95)

The only issue now is that some lightning effects surrounded some turrets are visible through terrain. I'm not sure where to find the code for that, though.
