### ISSUE TITLE
[Runtime Issue]: Rip out registry checks in favor of local config file

### ISSUE THREAD

**Issue by JeodC** [DescentDevelopers/Descent3#282]
### Description

Current source uses the system registry to store and retrieve settings data. This should be changed to a local config file for portability and multiple installations (considering forks).

**Comment by JeodC** [comment]
This is all done inside [init.cpp](https://github.com/DescentDevelopers/Descent3/blob/22bc56aa5f5ca694edfb9ed72f8f287bc0d4d049/Descent3/init.cpp#L1232) and is saved to `Computer\HKEY_USERS\userhash\Software\Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\Outrage\Descent3` on 64bit Windows machines.

**Comment by jcoby** [comment]
The linux registry.cpp may be possible to repurpose for all platforms. It uses an ini-like structure to store registry items.
