### ISSUE TITLE
Unwitting changes to files, are they okay?

### ISSUE THREAD

**Issue by Nakhr11n** [DescentDevelopers/Descent3#286]
#275 edits a lots of files that are only meant to be moved.
Some verification should be done to ensure this didn't break anything.

By running `git show --stat ef886a2cf2d7af3e1eabf3700acb1c6bbf61454d` you can clearly see the effect.
Or by looking closely at the "Files Changed" section of #275.

**Comment by JeodC** [comment]
This looks like a result of github conversion to UTF-8 and line endings. The string files I'm sure will need some care to be accurate to the languages.
