### ISSUE TITLE
[Build Failure]: Built TCP-IP.d3c is not built correctly

### ISSUE THREAD

**Issue by JeodC** [DescentDevelopers/Descent3#300]
### Build Version

current

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [ ] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Description

While #296 was a necessary step to get a d3c to build at all, it is 22KB vs. the 144KB expected size. As a result, using this protocol at the multiplayer menu does nothing.

[Hog2Workshop ](https://sectorgame.com/d3/downloads/?nav=display&file=29) is able to open `.d3c` files, but the compiled .d3c is not recognized as a hog2 file. 7-zip is normally unable to open .d3c files, yet will open this one like an executable with a .rsrc folder and contents.

**Comment by winterheart** [comment]
According to code, game expects to find the HOG2 file named as `Direct TCP~IP.d3c` with `Direct TCP~IP.so` or `Direct TCP~IP.dll` on it. We need generate that HOG in build process with HogMaker.
