### ISSUE TITLE
[Runtime Issue]: Descent 3 lighting bugs

### ISSUE THREAD

**Issue by DAK404** [DescentDevelopers/Descent3#320]
### Build Version

v1.5 9CB68C2

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [ ] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Game Environment

Descent 3 Mercenary Level 5: Start the level, enter into the circular structures, proceed to get into the tunnel (where a stone ball chases you). After that, there are doors that will lead you into a room with blue lighting and with lot of robots and turrets.

### Description

Room is too dark, and on pressing ESC, the lighting is restored until the exit confirmation dialog is dismissed.

Screenshot when in game:
![Screenshot003](https://github.com/DescentDevelopers/Descent3/assets/46497387/68c4c205-0711-455d-a3ce-edbcb80e811d)

Screenshot when ESC is pressed:
![Screenshot004](https://github.com/DescentDevelopers/Descent3/assets/46497387/c3bcb5d0-24c0-49a9-8c84-c2fe33ed09a5)

**Comment by JeodC** [comment]
If you go to the registry at `Computer\HKEY_USERS\*\Software\Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\Outrage\Descent3` you should have a string called `RS_Gamma` that's set to 1.5. Try setting it to 1.0 and see if that helps.

**Comment by DAK404** [comment]
Tried it, but its the same with 1.0

With 1.0 Gamma in game:
![Screenshot005](https://github.com/DescentDevelopers/Descent3/assets/46497387/8f8d10a9-cc24-4007-af86-1ec9ffc4f83b)

With 1.0 Gamma when ESC is pressed:
![Screenshot006](https://github.com/DescentDevelopers/Descent3/assets/46497387/d4552712-0d28-491e-b49d-7cb633e773ea)

**Comment by DAK404** [comment]
I did not find the registry settings at `Computer\HKEY_USERS\*\Software\Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\Outrage\Descent3`

Rather it was at `Computer\HKEY_CURRENT_USER\Software\Outrage\Descent3`

I will manipulate the gamma in both the lowest and highest values, and then do it via registry.

**Comment by JeodC** [comment]
Per Discord discussions:

Merc Level 5 applies a dynamic lighting change after robots break out of cells in this room. Opening the pause menu turns off this change. This is normal behavior, then, but the user may wish for brightness to be adjustable more easily.

Piccu Engine accomplishes this, and @InsanityBringer is more than welcome to integrate it via PR.

**Comment by DAK404** [comment]
Here is the save file for convenience 😄 
[saveg002.zip](https://github.com/DescentDevelopers/Descent3/files/15267840/saveg002.zip)

**Comment by JeodC** [comment]
This is confirmed to be the same case on retail v1.4, as well as Piccu with their gamma commits, so this is now a feature request--and one that we aren't sure yet if we can do since the level itself is doing the lighting instructions. I think this should be closed for now.
