### ISSUE TITLE
[Runtime Issue]: Startup crash

### ISSUE THREAD

**Issue by JeodC** [DescentDevelopers/Descent3#330]
### Build Version

43b11574fda64739b6c33e2c00ae54308997fea8

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [ ] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Description

Get a startup crash, access violation. Sometimes no error shows.

### Regression Status

Last working: 1f94e623b24ef7bb5a1e4bc797842b2d806e70e3

The .png commit was tested separately before refactor 2 was merged.

**Comment by Arcnor** [comment]
Can't reproduce

**Comment by JeodC** [comment]
[gdb.txt](https://github.com/DescentDevelopers/Descent3/files/15277793/gdb.txt)

Attached gdb. Tried with and without movies.

**Comment by Lgt2x** [comment]
> [gdb.txt](https://github.com/DescentDevelopers/Descent3/files/15277793/gdb.txt)
> 
> Attached gdb. Tried with and without movies.

Too bad we don't have a full backtrace. The crash seems to happen during movie playback, last log being in `SubtInitSubtitles` function called by `PlayMovie`. The next log line is supposed to be issued by `mve_PlayMovie` function in `PlayMovie`, so the culprit is likely the `mve_PlayMovie` function. I likely not related to #323 changes

**Comment by JeodC** [comment]
> > [gdb.txt](https://github.com/DescentDevelopers/Descent3/files/15277793/gdb.txt)
> > Attached gdb. Tried with and without movies.
> 
> Too bad we don't have a full backtrace. The crash seems to happen during movie playback, last log being in `SubtInitSubtitles` function called by `PlayMovie`. The next log line is supposed to be issued by `mve_PlayMovie` function in `PlayMovie`, so the culprit is likely the `mve_PlayMovie` function. I likely not related to #323 changes

But that function hasn't changed at all between the two commits.

**Comment by JeodC** [comment]
![image](https://github.com/DescentDevelopers/Descent3/assets/47716344/0d92fea8-ebc3-4151-b87d-84504f9aaf62)

I could be wrong, but I think it might be failing to draw the loading screen bitmap. It would do this in the background as the movies play.

**Comment by JeodC** [comment]
Resolved with #331, need to wait for rebase and removed debugging symbols to merge.
