### ISSUE TITLE
[Runtime Issue]: Saving will crash game

### ISSUE THREAD

**Issue by donotsharepersonalinformation** [DescentDevelopers/Descent3#350]
### Build Version

07262f6

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Description

When doing a save while playing, the game will crash. Further actions to load or save through the main menu, ALT-F2 or F9 in game, again will also crash the game as it appears look at the corrupted save and not like it. Access to these windows will no longer work until save file is deleted from savegame directory.
Terminal output before the game dies is: 
```
double free or corruption (top)
SIGNAL 6 caught, aborting
```
Trying to load said file will output the following:
```
Descent 3 Message(Error: Reading file </home/dangermouse/.wine/drive_c/Games/Descent3/savegame/saveg000>: error = Unexpected end of file
)
```

### Steps to Reproduce

1. Start the game with the `07262f6` build. 
2. ALT-F2 or F9 will bring up the window to save the game.
3. Name the save and hit Ok.
4. Game should stop responding.

**Comment by winterheart** [comment]
Crash appears on rendering thumbnail image of save game. #348 should solve game crash on double free. Another issue is game  cannot correctly handle with corrupt savegames.

**Comment by Lgt2x** [comment]
Confirming that #348 solves the game save problem. Opening #351 for the corrupted file load
