### ISSUE TITLE
[Runtime Issue]: Incomplete save files will crash the 'load game' menu

### ISSUE THREAD

**Issue by Lgt2x** [DescentDevelopers/Descent3#351]
### Build Version

ad7c384

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Description

Corrupted/Empty save files will make selecting the "load game" menu crash the game. Related to #350 

### Steps to Reproduce

Assuming `~/Descent` is the game directory, 
```bash
touch ~/Descent/savegame/saveg001
Descent3 -setdir ~/Descent```
Launch the game, and select "Load game" menu to crash

**Comment by winterheart** [comment]
Crash is generated by incorrect handling of CFileReadBytes() exception in LoadGameDialog() (or, to be precise, no handling at all). Commenting out this throwing https://github.com/DescentDevelopers/Descent3/blob/main/cfile/cfile.cpp#L924 fixes crash, but I still cannot get it work with `try .. catch` block.
