### ISSUE TITLE
[Runtime Issue]: Sometimes level 5’s cutscene doesn’t fill the screen

### ISSUE THREAD

**Issue by Jayman2000** [DescentDevelopers/Descent3#365]
### Build Version

v1.5.0 56E61275

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Game Environment

I’m running NixOS 23.11 and using game data from the Windows Dual-Jewel version of Descent 3 v1.4.

### Description

If you start a new game on Descent 3: Retribution level 5, then the intro cutscene will fill the entire screen. However, if you start on a different level and then make it to level 5, the intro cutscene will only fill the top left corner of the screen.

### Regression Status

I don’t know.

### Steps to Reproduce

1. Run the game with a resolution that’s larger than the title screen’s resolution:
    ```
    ./Descent3 --width 1920 --height 1080 --aspect 1.7777778
    ```
3. Start a new game on any level of Descent 3: Retribution.
4. Type in the MORECLANG cheat code.
5. Warp to level 5.

**Comment by JeodC** [comment]
Try #289 and see if it still occurs.

**Comment by Jayman2000** [comment]
> Try #289 and see if it still occurs.

It still occurs.

**Comment by JeodC** [comment]
Confirmed within windows.
