### ISSUE TITLE
[Runtime Issue]: Multiplayer through Direct TCP/IP failing to load module

### ISSUE THREAD

**Issue by ExperimentIV** [DescentDevelopers/Descent3#369]
### Build Version

a8a80880b1a09255c18ead571e88756f87e66f72

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [ ] Single player
- [X] Anarchy
- [X] Hyper-Anarchy
- [X] Robo-Anarchy
- [X] Team Anarchy
- [X] Capture the Flag
- [X] Bounty
- [X] Entropy
- [X] Hoard
- [X] Monsterball
- [X] Cooperative

### Description

When trying to start a multiplayer game through the client with Direct TCP/IP you will get an error, `Error initializing game module`, when anything is selected and you try to start the game. Further selections after that error will say `This mission is not compatible with the selected multiplayer mode.` no matter what mode or type of game you choose. Exiting back to the main menu will revert things back to the initial error of module error when tried again.

### Steps to Reproduce

1. Load the game.
2. Click the Multiplayer menu.
3. Select Direct TCP/IP and hit OK.
4. Select `Start a new game` at the top.
5. Select any combination of server options.
6. Select `Start Game`

**Comment by Jayman2000** [comment]
I can confirm this bug report. I was able to reproduce this issue while using 3c74b79667a9fb9de1aca5ac583302bbd0a528da on NixOS 23.11.

I think that one of my existing PRs fixes this issue, so I linked it to this issue. (I tried reproducing this issue with my PR, and I couldn’t). Could you test out #297 to make sure that it fixes this issue?

**Comment by donotsharepersonalinformation** [comment]
> I can confirm this bug report. I was able to reproduce this issue while using [3c74b79](https://github.com/DescentDevelopers/Descent3/commit/3c74b79667a9fb9de1aca5ac583302bbd0a528da) on NixOS 23.11.
> 
> I think that one of my existing PRs fixes this issue, so I linked it to this issue. (I tried reproducing this issue with my PR, and I couldn’t). Could you test out #297 to make sure that it fixes this issue?

I was able to check that branch, and it does appear to fix the issue that I am having in this ticket on quick glance.
