### ISSUE TITLE
Loss of PR #268

### ISSUE THREAD

**Issue by GravisZro** [DescentDevelopers/Descent3#391]
PR #268 has been lost as a the result of a bad merge.

This impacts 575 files, so it will not be rebased again. Please reset the main branch to 9c039e6d2c8b2a33531cf1aeb758e5d14c291085, rebase on https://github.com/GravisZro/Descent3/tree/use/stdint and then cherry-pick the new commits and resolve any conflicts.

**Comment by winterheart** [comment]
Sorry, we cannot reset main at any previous commit as it breaks whole repository flow. If you feel that something amiss, prepare new PR with additional changes.

**Comment by bryanperris** [comment]
![commits](https://github.com/DescentDevelopers/Descent3/assets/7431407/a7bd5f1e-11be-427f-9aa1-1e0fc3fc8fd8)

**Comment by GravisZro** [comment]
@winterheart Do you not understand how to do so or are you simply unwilling? Please see #393

**Comment by GravisZro** [comment]
@bryanperris Just know that I'm not doing it again, it's either recover now or go forever without it because I know if I do it again, the same thing will happen and I'll be told, "Sorry, we cannot reset main at any previous commit as it breaks whole repository flow." again.

**Comment by winterheart** [comment]
I am unwilling (and I cannot, by the way) doing thing that definitely breaks repository and current work for all users just by request from you. So please, explain, what is lost during merge of #268, propose fix in constructive manner and stop hate speech behavior.

Participation in this project is voluntary, but no one will voluntarily do anything that will harm the project. Resetting the main branch to an arbitrary commit (where other changes after yours have already been merged) is harmful to the project.

**Comment by bryanperris** [comment]
> @bryanperris Just know that I'm not doing it again, it's either recover now or go forever without it because I know if I do it again, the same thing will happen and I'll be told, "Sorry, we cannot reset main at any previous commit as it breaks whole repository flow." again.

Please clarify for me on what you mean when you say "bad merge", the screenshot shows all your commits and then a commit specifically identifying your PR and number was merged into main.

**Comment by GravisZro** [comment]
@bryanperris A bad merge means an old version of the repository was merged into the current version of the repository. The result is that the history of the repo is altered. Here's the merge from the git log.

```
commit a77fdd74268a73c707aac940b087fc35c046b089
Merge: 9c039e6 5e5e0c9
Author: Louis Gombert <44813937+Lgt2x@users.noreply.github.com>
Date:   Fri May 24 11:00:28 2024 +0000

    Merge pull request #268 from GravisZro/use/stdint
    
    Refactor to fixed width integer types: proven to be free of errors
```

**Comment by bryanperris** [comment]
Let say in my PR, I do the squash commits, and then rebase my branch based on the latest main, then won't the merge be clean as well?  From my past experience working on bitbucket repositories, the team lead will enforce that everyone just create a PR, make sure all your commits are squashed down into just one, then make sure to rebase too, then when that is all set, it gets merged.  This is referring to industrial codebases between medical applications and then government ones.  

Let me you ask you this, do you only use git CLI for all git management?

**Comment by GravisZro** [comment]
I don't mind people squashing commits, that's not only fine, it's expected. I'm not sure what happened but I'm seeing the commits made in the github log again. I'm not sure exactly what happened.

> From my past experience working on bitbucket repositories, the team lead will enforce that everyone just create a PR, make sure all your commits are squashed down into just one, then make sure to rebase too, then when that is all set, it gets merged. 

Yep, this is my experience too. I really wish that is how it was done here because then you don't have to wonder if the git history is real or revised.

> Let me you ask you this, do you only use git CLI for all git management?

Yes.

**Comment by bryanperris** [comment]
recently I been using this tool for work, I think its pretty useful: https://github.com/jesseduffield/lazygit

**Comment by GravisZro** [comment]
It looks very nice. Not to be too much of a purist but I'm not thrilled that it's written in Go but at least it's an actual compiled language. The worst is when there is a CLI tool written in javascript and uses npm to pull in many different packages so it becomes an instant security trash fire.

Building something in JavaScript is like building a Utopian society: a great concept with a horrifying reality.

**Comment by bryanperris** [comment]
yeah npm is not my favorite thing.  I didn't realize it was written in Go.

**Comment by JeodC** [comment]
Just to add @GravisZro your PRs are also pulled to my fork, so it doesn't appear there was any loss of commits.

![image](https://github.com/DescentDevelopers/Descent3/assets/47716344/519da7fd-8709-4d0e-9186-c9f2c01f69b6)
