### ISSUE TITLE
Reconfigure Descent3 repository to enforce rebasing

### ISSUE THREAD

**Issue by GravisZro** [DescentDevelopers/Descent3#392]
[I have previously warned about the dangers of using merge](https://github.com/DescentDevelopers/Descent3/discussions/228#discussioncomment-9277532) and those warnings were tersely dismissed. However, we are now losing PRs on a regular basis, so I advise that the github repository for Descent3 be reconfigured to only allow commits by rebasing.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-rebasing-for-pull-requests

**Comment by winterheart** [comment]
Nothing is lost on #268 merge. Merging PR instead of rebasing is normal practice that has some advantages upon rebasing such reverting commits and more suitable on collaborative work.

**Comment by GravisZro** [comment]
> Merging PR instead of rebasing is normal practice that has some advantages upon rebasing such reverting commits

You literally refused to undo anything, so what good is a feature that will not be used?

> more suitable on collaborative work.

I disagree. It seems to be exactly the opposite. Rebasing ensures that the commit is up to date with the repo and ensure the git history is immutable.

Also, notice you closed this without a response because you deemed the problem to not be a problem which the exact behavior I've outlined in #393.
