### ISSUE TITLE
[Runtime Issue]: Game hangs on starting on first second of Dolby Digital intro

### ISSUE THREAD

**Issue by winterheart** [DescentDevelopers/Descent3#398]
### Build Version

4ac9b9c22f34c0605470f5ce4a6b51db1cd32b4f

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Description

Game hangs on first second of Dolby Digital intro (looping first sample).

### Regression Status

Bisected log reveals that first issue appeared in 4ac9b9c22f34c0605470f5ce4a6b51db1cd32b4f

### Steps to Reproduce

Compile project from latest main, try to run Descent3.

**Comment by winterheart** [comment]
Related PR #356.

**Comment by Lgt2x** [comment]
Confirming the issue and bad commit
