### ISSUE TITLE
[Runtime Issue]: ./Descent3: /lib64/libncurses.so.6: version `NCURSES6_5.0.19991023' not found (required by ./Descent3)

### ISSUE THREAD

**Issue by DAK404** [DescentDevelopers/Descent3#404]
### Build Version

v1.5 <0ff98a7> and below

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [ ] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Description

OS: Linux
Distribution: OpenSUSE Tumbleweed

Seems like if i try to run `Descent3` the game does not start. Therefore, starting the game in terminal, the following output is seen:

`./Descent3: /lib64/libncurses.so.6: version `NCURSES6_5.0.19991023' not found (required by ./Descent3)`

I did try to grab `ncurses-devel` but it did not help.

I am unsure if it is a game issue or if it is something on my end.

**Comment by winterheart** [comment]
I guess you've downloaded Descent 3 binary from artifacts page on Github Actions? If so, executable was linked with Ubuntu's ncurses library which may be incompatible with yours.

You may compile Descent 3 by self using [building instructions](https://github.com/DescentDevelopers/Descent3?tab=readme-ov-file#building) and try it on your Linux environment.

**Comment by DAK404** [comment]
I'll give it a try soon, will update once i do so!

**Comment by Lgt2x** [comment]
The dynamic loading of the library in `dyna_curses.h` is a problem in itself and should be removed

**Comment by GravisZro** [comment]
> The dynamic loading of the library in `dyna_curses.h` is a problem in itself and should be removed

I disagree completely because ncurses shouldn't be a requirement _unless_ you are running dedicated server mode because it's the **ONLY** place it's used.

**Comment by Lgt2x** [comment]
> > The dynamic loading of the library in `dyna_curses.h` is a problem in itself and should be removed
> 
> I disagree completely because ncurses shouldn't be a requirement _unless_ you are running dedicated server mode because it's the **ONLY** place it's used.

Opening the library via `dl_open` when you need it is not the way you setup an optional library dependency, see how that breaks the game in this situation. Dedicated server mode should be hidden behind a compilation option that requires ncurses.

**Comment by winterheart** [comment]
As far I can tell, there only one symbol from ncurses is used and I don't see what is so important, that require whole external dependency. Better to rid of it completely.

**Comment by GravisZro** [comment]
> Dedicated server mode should be hidden behind a compilation option that requires ncurses.

If you do that then you end up with linking errors due to various version of the library and which distribution you use. That is **exactly** what happened to the person who opened the ticket.

**Comment by GravisZro** [comment]
> As far I can tell, there only one symbol from ncurses is used

And you would be wrong.

**Comment by Lgt2x** [comment]
What do you suggest to fix the problem then?

**Comment by GravisZro** [comment]
> What do you suggest to fix the problem then?

The obvious solution is to utilize dynamic loading.  There aren't any drawbacks to using dynamic loading which is why your opposition to it has taken me by surprise.

We should be dynamically loading everything except for libc, just like the original D3 did. The choice to use dynamic loading wasn't a fluke, it was a wise decision. It's the reason that D3 would work with any Linux distro using a compatible glibc (which they also distributed) while the dependencies were able to be dealt with in a way that didn't require package versioning. However, we have the advantage of being able to statically link libc on Linux which would make D3 exceptionally portable. The way we're going now, any installation package made will need to be updated every few months for every distro not because changes need to be made to the code but to keep the library versions used by D3 in sync with each distro, something not needed with dynamic loading.

I don't know who decided that dynamic loading should be discarded but they should seriously reconsider.

**Comment by JeodC** [comment]
IIRC nobody decided it--it was never a policy, just an approach. The last time I recall any discussion of it happening was when I brought up a general philosophy of having as few third party dependencies as possible. Some of the decision to make libraries static may have been born from that.

But, unlike windows, the mac and linux steam releases statically link a chunk of their libraries; I know dmfc is static there.

**Comment by GravisZro** [comment]
> But, unlike windows, the mac and linux steam releases statically link a chunk of their libraries; I know dmfc is static there.

Statically linking everything is an option... but load-time shared link libraries are the worst of all options.

**Comment by JeodC** [comment]
Right I'm only saying that there was no executive decision on any policy for this sort of thing.

**Comment by GravisZro** [comment]
There definitely should be because as of this ticket, it's an issue.

**Comment by winterheart** [comment]
Ncurses gets loaded only when `-svgalib` and `-dedicated` options is called. Without `-svgalib` game uses `Console_raw` mode. Assuming that svgalib is pretty ancient technology on Linux and in-game support somehow already broken on arrival (I cannot properly use it in modern Linux system), I suggest just strip `Console_normal` mode which also removes ncurses dependency requirement.

**Comment by GravisZro** [comment]
@winterheart is correct that curses is only loaded in combination with `-svgalib`. I used the flag and the actual `dlopen` function failed which seems to be a result of linker options. I'm investigating further to see if it's worth saving or if we should exclude curses entirely. One thing is certain, it should not be an execution requirement.

**Comment by Lgt2x** [comment]
See #407 removing ncurses entirely

**Comment by DAK404** [comment]
I just tested the #407 binaries created by GitHub actions.

I can now confirm that the game launches successfully.
I did however find that when pressing "New Game" it asked me to insert Descent 3 CD 1. After pressing Ok, it launched the training mission successfully.
Additionally, the aspect ratio of the main menu is extremely stretched.

**Comment by winterheart** [comment]
Yes, these issues are expected on current stage of project development (except message about inserting CD. I thought we removed this part of code). Aspect ratio is stretched because game menu internally runs on 640x480 and on widescreen monitors it stretched to fit to new resolution.

**Comment by JeodC** [comment]
Linux has different init in lnxmain, only init.cpp got cd calls and messages removed.

**Comment by JeodC** [comment]
> Linux has different init in lnxmain, only init.cpp got cd calls and messages removed.

Actually, spotted cd refs in lnxcdrom.cpp and gamesequence.cpp
