### ISSUE TITLE
[Runtime Issue]: Quitting the game causes “Debug Assertion Failed! `_CrtlsValidHeapPointer(block)`”

### ISSUE THREAD

**Issue by Jayman2000** [DescentDevelopers/Descent3#444]
### Build Version

v1.5 a059b14677204681030d41706b8296962cbb9be8

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [X] Anarchy
- [X] Hyper-Anarchy
- [X] Robo-Anarchy
- [X] Team Anarchy
- [X] Capture the Flag
- [X] Bounty
- [X] Entropy
- [X] Hoard
- [X] Monsterball
- [X] Cooperative

### Game Environment

I’m using game data from the Windows Dual-Jewel version of Descent 3 v1.4.

### Description

When I quit the game, this message appears:

![Microsoft Visual C++ Runtime Library&NewLine;&NewLine;Debug Assertion Failed!&NewLine;&NewLine;Program: …y mine\Descent3\main\builds\win32\Descent3\Debug\Descent3.exe&NewLine;File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp&NewLine;Line: 904&NewLine;&NewLine;Expression: _CrtlsValidHeapPointer(block)&NewLine;&NewLine;For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.&NewLine;&NewLine;(Press Retry to debug the application)&NewLine;&NewLine;Choose one of these options: Abort, Retry, Ignore](https://github.com/DescentDevelopers/Descent3/assets/5579359/b383d178-4a80-4cfc-bd22-d0631c4314c1)

### Regression Status

I don’t know.

### Steps to Reproduce

1. Run `Descent3 -nointro -pilot <pilot-name>`
2. Wait for the main menu to load.
3. Press <kbd>Q</kbd>.
4. Press <kbd>Y</kbd>.

**Comment by pzychotic** [comment]
This seems to be introduced by #436. Disabling the CMake option `ENABLE_MEM_RTL` fixes the problem for me.
