### ISSUE TITLE
[Runtime Issue]: Sounds and briefings are in german when locale is not supported

### ISSUE THREAD

**Issue by Lgt2x** [DescentDevelopers/Descent3#477]
### Build Version

#457

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [ ] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Description

Sound and briefing sounds on Windows (64bit SDL2 version) are in german when the system locale is not supported. Reported in #457 (https://github.com/DescentDevelopers/Descent3/pull/457#issuecomment-2198241046)

**Comment by winterheart** [comment]
Seems it's my misconfiguration setup. I've tested German version some time ago and forgot to reset it to default. After copying Steam files all messages switched back to English.
