### ISSUE TITLE
[Runtime Issue]: MVE playback crashes on launch with extra launch options

### ISSUE THREAD

**Issue by 0xFADDAD** [DescentDevelopers/Descent3#490]
### Build Version

https://github.com/DescentDevelopers/Descent3/commit/87f6ef009fbd7c5c07ddd38bde196b59494823e3

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [ ] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Game Environment

Launching with the following options:
`./Descent3 -width 1920 -height 1200 -aspect 1.6 -framecap 360 -nomotionblur -usesmoothing`
causes Dolby intro to flash a single frame and crash with the following:
SIGNAL 11 caught, aborting
malloc_consolidate(): unaligned fastbin chunk detected
Recursive signal cleanup! Hard exit! AHHGGGG!

### Description

Good possibility of an audio initialization issue.
Game launches fine with `-nointro` option, and campaign intro's play fine, but with increasing audio desync. (video runs faster than audio)

### Steps to Reproduce

launch game, receive error

**Comment by 0xFADDAD** [comment]
Extra context: when running the game with `-nosound` from https://github.com/DescentDevelopers/Descent3/pull/489 build, playback works.

**Comment by winterheart** [comment]
Crash happens because in some cases sound buffer gets empty and cannot fill SDL callback.

There are several flaws in the new MVE implementation that I plan to fix in the next iteration.
