### ISSUE TITLE
Descent 3 1.5 Release process

### ISSUE THREAD

**Issue by Lgt2x** [DescentDevelopers/Descent3#506]
We have now completed the minimum requirements initially set to make a first release of Descent 3 since its public code release on April 16th.

This issue tracks the release process for the first release of the game. Anyone is free to contribute to the following tasks, just say it here what you want to help with. Any order is fine, except for the last 2 items.

- [x] Changelog/Release notes: collect, group, sort and summarize changes from all merged PRs. Weekly summaries until 20/5 are available [here](https://github.com/DescentDevelopers/Descent3/wiki/Weekly-Updates) for rerefence
- [x] Test manually `release` branch on all supported platforms: Linux (at least Ubuntu, Fedora, Arch), Windows 10 and 11, Mac OS Intel and ARM chips, Raspberry Pi 64 bits. Testing include entering and completing levels from all campaigns, creating and joining a multiplayer game using TCP/IP or PXO, binding controls
- [x] Update project issues, test those that may be fixed alread.
- [x]  Disable shipping the internal level editor in the installed packaged. The editor is broken since the SDL2 transition, and would require additional work to get working again
- [x] Write a document attached with the game, listing the instructions to get it running : how to find game data on any given OS, how to run the game from there.
- [ ] clang-format the whole code base
- [x] Create the v1.5.0 tag from `release` branch
- [ ] Outreach: post about the release on both Discord servers, Reddit, forums, and other outlets we can access

**Comment by JeodC** [comment]
You've got #130 and #279 left on the 1.5 milestone list. #130 I think may already be resolved pending a test, and #279 hasn't had any activity for some time.

**Comment by Lgt2x** [comment]
> You've got #130 and #279 left on the 1.5 milestone list. #130 I think may already be resolved pending a test, and #279 hasn't had any activity for some time.

Oh I did not mention it but we decided to drop #279 for this release after some investigation, it looks very complicated to get structure alignment right. #130 should be fixed with the mve revamp. I've added an item for processing remaining open issues
