### ISSUE TITLE
[Runtime Issue]: New renderer slowing down the game

### ISSUE THREAD

**Issue by Lgt2x** [DescentDevelopers/Descent3#543]
### Build Version

45ff821

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [X] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [ ] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [X] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [ ] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Description

Following #527 , rendering issues have been experienced, as well as noticeable FPS drop

Video example by @MaddTheSane 

https://github.com/user-attachments/assets/56d7c69b-cb43-4c3f-8bef-9c950e22df03

**Comment by MaddTheSane** [comment]
I can say that #545 fixes this issue.
