### ISSUE TITLE
[Runtime Issue]: libmve audio dropping out under Linux with PipeWire audio.

### ISSUE THREAD

**Issue by KynikossDragonn** [DescentDevelopers/Descent3#551]
### Build Version

v1.5

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [ ] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Description

I don't know what libmve is trying to set as a buffer but I get audio drop outs/sync issues under Linux probably because of this ridiculously high `QUANT` value being set on libmve's separate audio source.

the SDL2 sound is fine though.

![Screenshot_2024-08-28_17-18-08](https://github.com/user-attachments/assets/cf9c2609-7f87-4e95-8ce5-2a6a553c1f43)

### Regression Status

I don't know.

### Steps to Reproduce

Run under Linux with the PipeWire audio server setup and use `SDL_AUDIODRIVER=pipewire` before launching Descent 3 natively.

Every cutscene handled by libmve has a much higher `QUANT` value than the main SDL2 audio handler initially created by Descent 3.

**Comment by winterheart** [comment]
Hello.
Can you please test changes from #552 PR?

**Comment by KynikossDragonn** [comment]
I'm seeing proper `QUANT` values after patching the 1.5.0 tarball with these changes.

Audio isn't dropping out in MVE playback anymore.
