### ISSUE TITLE
[Runtime Issue]: Cannot move levers/switches or pick up keys in 3rd party levels

### ISSUE THREAD

**Issue by sirken** [DescentDevelopers/Descent3#583]
### Build Version

v1.6.0 705c67a1be01741a1fa81c9d84e975daccdc3143

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [X] Cooperative

### Game Environment

Manjaro 2024-09 x64 (using workflow builds)
Linux Mint 20.x x64 (compiled builds)

These are only some of the level examples we tested, all in single player, some in coop. We tried many others too, all exhibiting the same behaviour
- Defcon1
- Darkmoon
- Ahawyeh Gate Revamped
- Alien Territory
- Centroid

### Description

Originally we were playing a 3rd party coop level (don't recall which one), but none of the levers would move, and so the level could not be completed. We tried a few others, and found that keys could not be picked up either. So far none of the 3rd party SP maps we've tried, in coop or single player, have had working levers or keys. We only tested single player and cooperative, so not sure if this affects other game modes or not

Initially we were using the 1.5.0 release. Since then we compiled a few newer commits, the latest one being `705c67a` without any different results

The original levels are working as expected and have _not_ had the same problems

https://github.com/user-attachments/assets/92f1b127-e5e7-476b-901a-a609e6dca48d

https://github.com/user-attachments/assets/81811035-493c-48af-bce2-845955cfea1b

**Comment by Lgt2x** [comment]
Hi, thanks for the report. Unfortunately, one big shortcoming of our Descent 3 port currently is the lack of support for legacy x86 level scripts. As we now target x64 systems, old custom level code cannot run properly without being recompiled for x64 systems. Main campaign level scripts are now compiled for x64, but we don't always have access to the code for old levels. Different solutions have been suggested, including portable x86 emulation inside of the game engine, but it won't be available in the near future. We hope to address that in a later release.

**Comment by sirken** [comment]
Ah, that's very interesting -- I wasn't aware of how things worked under the hood and that makes a lot of sense. Good to know it's on the radar, and thank you for the detailed explanation.

Looking forward to where this project is heading, thank you for all your collective work on it!
