### ISSUE TITLE
[Runtime Issue]: Debug break when starting Pilot Training

### ISSUE THREAD

**Issue by Jayman2000** [DescentDevelopers/Descent3#605]
### Build Version

v1.6 c5630268c244efb8cc1f1d967c09923915958433

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Game Environment

I’m using game data from the US Windows Dual-Jewel version of Descent 3 v1.4.

### Description

Starting the Pilot Training mission on Windows will give you this error:

![Descent 3 Debug Break&NewLine;&NewLine;Int3 in C:\Users\Anon Y. Mous\Documents\Descent3-backup\Descent3\OsirisLoadandBind.cpp at line 1005.&NewLine;&NewLine;It's probably safe to continue.  Continue?&NewLine;&NewLine;Choose one of these options: Yes or No.](https://github.com/user-attachments/assets/7cf0393f-2972-4e53-93c4-78a1a35cc0f6)

### Regression Status

Newest commit that doesn’t have the problem: 2d29dd4f7c76bb9474103435d587dae61b922dfb
Oldest commit that does have the problem: 09ab370821ee37cc3bea66e43a34bb21f792d503

### Steps to Reproduce

1. Start a debug build of Descent 3 on Windows.

2. Once you get to the main menu, click “New Game”.

3. If you’re prompted to select a mission, then select “Pilot Training”.

**Comment by winterheart** [comment]
This Int3() happens on inability to load level module. Did you copied platform-dependent `d3-win.hog` into Base_directory (where Descent3.exe is placed)?

**Comment by Jayman2000** [comment]
> This Int3() happens on inability to load level module. Did you copied platform-dependent `d3-win.hog` into Base_directory (where Descent3.exe is placed)?

`d3-win.hog` and `Descent3.exe` are in the same directory.
