### ISSUE TITLE
Source for hogUtils-i686

### ISSUE THREAD

**Issue by Nakhr11n** [DescentDevelopers/Descent3#61]
`hogUtils-i686 (scripts/hogutils/hogUtils-i686)` is executed as part of the build system to build hog files.
However, it is a linux 32-bit executable, which means that extra steps are required for building on anything other  than 32-bit linux.
It would be nice to have the source for this, so it can be built as part of the build system, and thus be native to whatever system it is used on.

**Comment by winterheart** [comment]
After some digging code I can tell that we can write own tool to make HOG files. All needed code already here in hogfile.h / hog.cpp. If there nothing special on generated hogs (like a messing with headers after generation), it would be easy task.

**Comment by winterheart** [comment]
OK, actually hogUtils actually is here in source code: https://github.com/kevinbentley/Descent3/blob/main/Descent3/lnxmain.cpp#L550. Still it's unpractical to build custom version of Descent executable, so I decided write own version of hogUtils and possibly some of cfile components.

**Comment by mstephenson6** [comment]
I ran into the same problem building on linux aarch64, I have a Dockerfile almost working that just wraps the thing in a Debian i386 container so the hog file generates for me.

**Comment by mstephenson6** [comment]
See #98 for my short term workaround, but +1 to a replacement.

**Comment by kevinbentley** [comment]
I added some code in a branch, not sure if this helps resolve the issue:

https://github.com/kevinbentley/Descent3/tree/add-missing/hogmaker
https://github.com/kevinbentley/Descent3/tree/add-missing/hogedit

**Comment by bryanperris** [comment]
Would it make sense these for these build tools live in the repo as python scripts instead?

**Comment by kevinbentley** [comment]
I'd favor just adding it to cmake so a build generates the executable. Unless someone wants to port the whole thing to python, which IMO is unnecessary.
