### ISSUE TITLE
The option to invert the Y-axis should be more obvious

### ISSUE THREAD

**Issue by Jayman2000** [DescentDevelopers/Descent3#62]
(This issue was inspired by #56).

[You can play Descent 3 with an inverted Y-axis](https://support.gog.com/hc/en-us/articles/4407602848913-Descent-3-Mercenary-How-to-invert-controls?product=gog), but the option is so hidden that a lot of people don’t know about it. There should be a more obvious way to invert the Y-axis because of how many people want to play with an inverted Y-axis.

The way Overload handled this was perfect. While you’re playing Overload’s tutorial, it will ask you if the Y-axis feels right, and tell you to press a button if you want to invert it. It would be cool if we could do something similar. Or perhaps we could add a pop-up window that asks the player if they want to invert their Y-axis when they create their pilot.

**Comment by JeodC** [comment]
I think it's worth considering enabling by default to mitigate motion sickness caused by snappy mouse movements.

**Comment by Jayman2000** [comment]
> I think it's worth considering enabling by default to mitigate motion sickness caused by snappy mouse movements.

How would enabling it by default mitigate motion sickness caused by snappy mouse movements?

**Comment by JeodC** [comment]
> > I think it's worth considering enabling by default to mitigate motion sickness caused by snappy mouse movements.
> 
> How would enabling it by default mitigate motion sickness caused by snappy mouse movements?

Wrong subject--was considering an example video I saw that compared flightsim mode to mouselook. I believe those are covered in the game's tutorial if I'm not mistaken.

I kept reading about people not playing through the game back in the day due to motion sickness--was looking for the reason for it.

**Comment by bryanperris** [comment]
Wow, never knew that, however if playing the game with NVIDIA's 3D glasses from the early 2000s, yeah I can see that.

**Comment by JeodC** [comment]
I believe this will be revisited post-1.5 release.
