### ISSUE TITLE
Loading any demo play file for native linux results in crash

### ISSUE THREAD

**Issue by bryanperris** [DescentDevelopers/Descent3#8]
How to reproduce:
1. Install the game from Steam on a linux based system (Steam Deck for me)
2. From the main menu, select demo and pick any demo file
3. Process will crash

**Comment by Jayman2000** [comment]
I don’t think that this is the right place to report that bug. The Linux/macOS version of Descent 3 that’s on Steam was created by icculus. [Unfortunately, he hasn’t gotten permission in order to release his version of the code yet.](https://github.com/kevinbentley/Descent3/issues/9) The code in this repo doesn’t contain any of his changes. Issues with icculus’s version of the game should be reported [here](https://github.com/icculus/descent3-bugs).

Are you able to reproduce this bug if you build the source code that’s in this repo?

**Comment by bryanperris** [comment]
If someone uploads a compiled D3 build for linux, I can test it out on my machine.  I guess anyone that manages to get the source built on linux and just quickly check if any demo file is able to play without crashing.  I filed issues as soon this code was realized based on my SteamDeck D3 experience, not knowing much of much of which source repo was used for the Steam release. This weekend I plan to just clone the repo when I get time, and attempt to compile it myself.

**Comment by bryanperris** [comment]
It seems the crash issue does exist for demo play, I have caught something in GDB

`Thread 1 "Descent3" received signal SIGSEGV, Segmentation fault.
0x0000000000677157 in hlsSystem::ComputePlayInfo (this=0x1339040 <Sound_system>, sound_obj_index=0, virtual_pos=0x7fffffffbb90, virtual_vel=0x7fffffffbb84, 
    adjusted_volume=0x7fffffffbb80) at /ho`

**Comment by bryanperris** [comment]
I attempted to play a demo file, and then bad demo file is displayed, here is a GDB log

Int3 in /home/bperris/base/dev/Descent3/Descent3/loadstate.cpp at line 769.(Descent 3 Debug Break)

System Error

It's probably safe to continue.  Continue?

Thread 1 "Descent3" received signal SIGTRAP, Trace/breakpoint trap.
trap_instruction () at /home/bperris/base/dev/Descent3/lib/debugbreak.h:48
48	}
Missing separate debuginfos, use: dnf debuginfo-install xorg-x11-drv-nvidia-libs-550.67-1.fc39.x86_64
(gdb) c
Continuing.

Int3 in /home/bperris/base/dev/Descent3/Descent3/OsirisLoadandBind.cpp at line 2680.(Descent 3 Debug Break)

System Error

It's probably safe to continue.  Continue?

Thread 1 "Descent3" received signal SIGTRAP, Trace/breakpoint trap.
trap_instruction () at /home/bperris/base/dev/Descent3/lib/debugbreak.h:48
48	}
(gdb) c
Continuing.

Thread 1 "Descent3" received signal SIGSEGV, Segmentation fault.
0x000000000053ae1a in ObjUnlink (objnum=3) at /home/bperris/base/dev/Descent3/Descent3/object.cpp:1478
1478	      seg->objects = obj->next;
