### ISSUE TITLE
libacm crash in UnpackLinear

### ISSUE THREAD

**Issue by MaddTheSane** [DescentDevelopers/Descent3#83]
When running on an Apple Silicon Mac, I've run into an issue with libacm, specifically the `InternalAudioDecoder::UnpackLinear` function.

https://github.com/kevinbentley/Descent3/blob/1edaa3b628b6945f93f7fde453967e244fabb45b/libacm/libacm.cpp#L574-L589

It seems like when `id` is 9 (and thus `middleIndex` gets set to *256*) and `offset` gets set to 255, it results in trying to get a negative address at `decoder.m_pMidBuffer`, which causes a crash.

**Comment by JeodC** [comment]
Maybe do something like this?
```cpp
     if (offset < middleIndex) {
       //Set pBlock[pos] to a default value, return false, or log an error
     }
 ```
 
 This would go above
 ```cpp
      const uint32 pos = (i << level) + col; 
     pBlock[pos] = decoder.m_pMidBuffer[offset - middleIndex]; 
     ```

**Comment by kevinbentley** [comment]
I've been debugging this same issue under Linux. I've been playing whack a mole trying to catch all the negative values, but we need to get to the root of the problem. It might be worth looking at switching to this library, which must be pretty good because it's part of ffmpeg now. [https://github.com/markokr/libacm](https://github.com/markokr/libacm)

**Comment by midnite8177** [comment]
I bet GetBitsEOF has the bug
Probably worth trying out that library

**Comment by midnite8177** [comment]
Marko Kreen wrote the original libacm, so this must be related

**Comment by bryanperris** [comment]
What about creating unit tests?

**Comment by devint1** [comment]
The issue seems to be that the C++ compiler treats `offset - middleIndex` as `uint32` instead of `sint32`.

This seems to fix the issue for now: 

```cpp
// pBlock[pos] = decoder.m_pMidBuffer[offset - middleIndex]; 
pBlock[pos] = decoder.m_pMidBuffer[((sint32) offset) - middleIndex];
```

**Comment by DanielGibson** [comment]
The libacm code in this repo is very different than the upstream code (which is plain C).
Might make sense to import and use the current libacm code https://github.com/markokr/libacm/? Probably has this and other bugs fixed

**Comment by paines** [comment]
I just checked https://github.com/markokr/libacm . This one compiles and runs fine on M1. I used [HUMAN1.ACM](https://sembiance.com/fileFormatSamples/audio/interplayACM/HUMAN1.ACM) with acmtool to test it.

**Comment by Jayman2000** [comment]
You can work around this problem by running Descent 3 with the `--nosound` option.

**Comment by DanielGibson** [comment]
Done, see #135
